#!/bin/bash

# Check if gedit is running
if pgrep "grive" > /dev/null
then
  echo "Sync already running"
else
  today=$(date +"%Y%m%d")
  lastsync=$(cat /home/inkless/lastsync)
  difference=`expr $today - $lastsync`
  power=$(cat /sys/class/power_supply/AC/online)

  # if over a day or if on AC power
  if [ "$difference" -gt "0" ] || [ "$power" -eq "1" ]
  then
    # check if Google Drive can be accessed
    if wget -O /dev/null -q https://drive.google.com;
    then
      grive -p /home/inkless/Google\ Drive/ -n
      echo $today > /home/inkless/lastsync
    else
      kdialog --passivepopup 'Google drive sync failed and sync is out of date' 3600
    fi
  fi
fi
